
name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      # Your original steps
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install package
        run: python -m poetry install
      - name: Generate Coverage report
        run: |
          python -m poetry run coverage run -m pytest ./tests/
          python -m poetry run coverage json
        env:
          ENTSOE_API_KEY: ${{ secrets.ENTSOE_API_KEY }}
      - name: Update Coverage Badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install package
      run: python -m poetry install
    - name: Test and lint package
      uses: microsoft/action-python@0.7.2
      with:
        pyright: false
        ENTSOE_API_KEY: ${{ secrets.ENTSOE_API_KEY }}
